[tool.pytest.ini_options]
# NexusPM Enterprise - Pytest Configuration (FIXED)
# Professional testing configuration for enterprise-grade quality assurance

# Basic Configuration
python_files = ["tests.py", "test_*.py", "*_tests.py"]
python_classes = ["Test*"]
python_functions = ["test_*"]
testpaths = ["backend/tests", "backend/apps"]

# Django Configuration
DJANGO_SETTINGS_MODULE = "config.settings.test"
addopts = [
    # Coverage reporting
    "--cov=apps",
    "--cov-report=html:htmlcov",
    "--cov-report=term-missing",
    "--cov-report=xml",
    "--cov-fail-under=85",
    
    # Test output formatting
    "--tb=short",
    "--strict-markers",
    "--strict-config",
    "--verbose",
    
    # Performance
    "--reuse-db",
    "--nomigrations",
    
    # Warnings
    "--disable-warnings",
]

# Test markers for categorization
markers = [
    "unit: Unit tests for individual functions/methods",
    "integration: Integration tests for multiple components",
    "functional: Functional tests for complete user workflows",
    "performance: Performance and load tests",
    "security: Security-related tests",
    "api: API endpoint tests", 
    "models: Model layer tests",
    "signals: Signal handling tests",
    "permissions: Permission and access control tests",
    "slow: Tests that take significant time to run",
    "external: Tests that require external services",
]

# Fixtures configuration
usefixtures = ["django_db"]

# Test discovery
norecursedirs = [
    ".*",
    "build", 
    "dist",
    "CVS",
    "_darcs",
    "{arch}",
    "*.egg",
    "venv",
    "env",
    "virtualenv",
    "node_modules",
    "frontend"
]

# Minimum version requirements
minversion = "7.0"

# Django database configuration for tests
django_find_project = false

# Filter warnings
filterwarnings = [
    "ignore::UserWarning",
    "ignore::DeprecationWarning",
    "ignore::PendingDeprecationWarning",
]