# Generated by Django 4.2.8 on 2025-10-23 00:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("organizations", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Workspace",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for this workspace",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Workspace name (e.g., 'Engineering Team', 'Client Projects')",
                        max_length=100,
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="URL-friendly identifier within the organization",
                        max_length=100,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Description of the workspace purpose and scope",
                    ),
                ),
                (
                    "workspace_type",
                    models.CharField(
                        choices=[
                            ("development", "Development Team"),
                            ("marketing", "Marketing Team"),
                            ("design", "Design Team"),
                            ("sales", "Sales Team"),
                            ("support", "Customer Support"),
                            ("operations", "Operations Team"),
                            ("finance", "Finance Team"),
                            ("hr", "Human Resources"),
                            ("general", "General Purpose"),
                            ("client", "Client Project"),
                        ],
                        default="general",
                        help_text="Type of workspace for better organization and UX",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("archived", "Archived"),
                            ("suspended", "Suspended"),
                        ],
                        default="active",
                        help_text="Current operational status of the workspace",
                        max_length=20,
                    ),
                ),
                (
                    "is_private",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this workspace is private (invitation-only)",
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        default="#3B82F6",
                        help_text="Hex color for workspace branding and UI",
                        max_length=7,
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        help_text="Icon identifier for workspace display",
                        max_length=50,
                    ),
                ),
                (
                    "settings",
                    models.JSONField(
                        default=dict,
                        help_text="Workspace-specific settings and preferences",
                    ),
                ),
                (
                    "project_count",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Cached count of active projects in this workspace",
                    ),
                ),
                (
                    "member_count",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Cached count of active members in this workspace",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        help_text="User who created this workspace",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_workspaces",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Workspace",
                "verbose_name_plural": "Workspaces",
                "db_table": "workspaces_workspace",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="WorkspaceMembership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("admin", "Workspace Admin"),
                            ("manager", "Project Manager"),
                            ("member", "Team Member"),
                            ("contributor", "Contributor"),
                            ("viewer", "Viewer"),
                        ],
                        default="member",
                        help_text="User's role within this workspace",
                        max_length=20,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this membership is currently active",
                    ),
                ),
                (
                    "invited_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the workspace invitation was sent",
                        null=True,
                    ),
                ),
                (
                    "joined_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="When the user joined this workspace",
                    ),
                ),
                (
                    "last_active_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="When the user was last active in this workspace",
                    ),
                ),
                (
                    "invited_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who invited this member to the workspace",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sent_workspace_invites",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User who is a member of this workspace",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workspace_memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        help_text="Workspace the user belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="workspaces.workspace",
                    ),
                ),
            ],
            options={
                "verbose_name": "Workspace Membership",
                "verbose_name_plural": "Workspace Memberships",
                "db_table": "workspaces_membership",
            },
        ),
        migrations.AddField(
            model_name="workspace",
            name="members",
            field=models.ManyToManyField(
                help_text="Users who are members of this workspace",
                related_name="workspaces",
                through="workspaces.WorkspaceMembership",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="workspace",
            name="organization",
            field=models.ForeignKey(
                help_text="Organization this workspace belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="workspaces",
                to="organizations.organization",
            ),
        ),
        migrations.AddIndex(
            model_name="workspacemembership",
            index=models.Index(
                fields=["workspace", "role"], name="workspaces__workspa_071777_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="workspacemembership",
            index=models.Index(
                fields=["user", "is_active"], name="workspaces__user_id_64f055_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="workspacemembership",
            index=models.Index(
                fields=["last_active_at"], name="workspaces__last_ac_f22023_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="workspacemembership",
            unique_together={("user", "workspace")},
        ),
        migrations.AddIndex(
            model_name="workspace",
            index=models.Index(
                fields=["organization", "status"], name="workspaces__organiz_a472da_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="workspace",
            index=models.Index(
                fields=["created_by"], name="workspaces__created_766472_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="workspace",
            index=models.Index(
                fields=["workspace_type", "status"],
                name="workspaces__workspa_ccb277_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="workspace",
            index=models.Index(
                fields=["is_private", "status"], name="workspaces__is_priv_1bb022_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="workspace",
            unique_together={("organization", "slug")},
        ),
    ]
